export const videos = [
  {
    id: 1,
    title: "Video from outside",
    pinpoint: [1],
    url: "video1.MOV",
  },
  {
    id: 2,
    title: "Front view of the pentadbiran building",
    pinpoint: [2],
    url: "video2.MOV",
  },
  {
    id: 3,
    title: "View of ground zero & entrace of dewan symphony",
    pinpoint: [3],
    url: "video3.MOV",
  },

  {
    id: 4,
    title: "Dewan Video",
    pinpoint: [4],
    url: "video4.MOV",
  },
  {
    id: 5,
    title: "Dewan Balcony Area",
    pinpoint: [4],
    url: "video5.MOV",
  },
  {
    id: 6,
    title: "Kecekalan Track",
    pinpoint: [5],
    url: "",
  },
  {
    id: 7,
    title: "Route to Kecekalan Track",
    pinpoint: [6],
    url: "video7.MOV",
  },
  {
    id: 8,
    title: "Tapak QM",
    pinpoint: [6],
    url: "video8.MOV",
  },
  {
    id: 9,
    title: "Route to Tapak QM",
    pinpoint: [6, 7],
    url: "video9.MOV",
  },
  {
    id: 10,
    title: "QM Cooking Area",
    pinpoint: [6],
    url: "video10.MOV",
  },
  {
    id: 11,
    title: "Bus Stop to Tapak Lelaki",
    pinpoint: [8],
    url: "video11.MOV",
  },
  {
    id: 12,
    title: "Tandas Lelaki",
    pinpoint: [9],
    url: "video12.MOV",
  },
  {
    id: 13,
    title: "Bus Stop",
    pinpoint: [8],
    url: "video13.MOV",
  },
  {
    id: 14,
    title: "Cabin AJK Lelaki",
    pinpoint: [11],
    url: "video14.MOV",
  },
  {
    id: 15,
    title: "Video of Tapak Perkhemahan Lelaki",
    pinpoint: [10, 11],
    url: "video15.MOV",
  },
  {
    id: 16,
    title: "Video of Tapak Perkhemahan Lelaki 2",
    pinpoint: [10],
    url: "video16.MOV",
  },
  {
    id: 17,
    title: "Riverside beside bus stop",
    pinpoint: [8],
    url: "video17.MOV",
  },
  {
    id: 18,
    title: "Carpark, Surau and Route to Flying Fox",
    pinpoint: [12],
    url: "video18.MOV",
  },
  {
    id: 19,
    title: "Carpark & Side of Pondok Pentadbiran",
    pinpoint: [2, 12],
    url: "video19.MOV",
  },
  {
    id: 20,
    title: "Tapak Perkhemahan Perempuan",
    pinpoint: [14],
    url: "video20.MOV",
  },
  {
    id: 21,
    title: "Route from Tapak Perkhemahan Perempuan to Pondok Pentadbiran",
    pinpoint: [12],
    url: "video21.MOV",
  },
  {
    id: 22,
    title: "Flying Fox Area",
    pinpoint: [15],
    url: "video22.MOV",
  },
  {
    id: 23,
    title: "Route from Fancy Cabin to Gazebo",
    pinpoint: [16],
    url: "video23.MOV",
  },
  {
    id: 24,
    title: "Drop-off point from flying fox",
    pinpoint: [16],
    url: "video24.MOV",
  },
  {
    id: 25,
    title: "Tribal council seats and route to Tapak Perkhemahan Perempuan",
    pinpoint: [14, 17],
    url: "video25.MOV",
  },

  {
    id: 26,
    title: "Route from bus stop to fancy cabin",
    pinpoint: [8, 18],
    url: "video26.MOV",
  },

  {
    id: 27,
    title: "Warning behind the fancy cabin",
    pinpoint: [18],
    url: "video27.MOV",
  },
];
