export const videos = [
  {
    id: 1,
    title: "Video from outside",
    pinpoint: [1],
    videoId: "Sp6Cdj7EyCw",
  },
  {
    id: 2,
    title: "Front view of the pentadbiran building",
    pinpoint: [2],
    videoId: "qXP-EnHWnmI",
  },
  {
    id: 3,
    title: "View of ground zero & entrace of dewan symphony",
    pinpoint: [3],
    videoId: "12Zh3EWWWxg",
  },

  {
    id: 4,
    title: "Dewan Video",
    pinpoint: [4],
    videoId: "TIK-e69Qbi0",
  },
  {
    id: 5,
    title: "Dewan Balcony Area",
    pinpoint: [4],
    videoId: "D5DK7DjUR7w",
  },
  {
    id: 6,
    title: "Kecekalan Track",
    pinpoint: [5],
    videoId: "hIIYDRpV-4s",
  },
  {
    id: 7,
    title: "Route to Kecekalan Track",
    pinpoint: [6],
    videoId: "B-9_GUhQeD4",
  },
  {
    id: 8,
    title: "Tapak QM",
    pinpoint: [6],
    videoId: "uEahiLKa0_4",
  },
  {
    id: 9,
    title: "Route to Tapak QM",
    pinpoint: [6, 7],
    videoId: "68CDuFP_N4I",
  },
  {
    id: 10,
    title: "QM Cooking Area",
    pinpoint: [6],
    videoId: "1qo5o2wQm1A",
  },
  {
    id: 11,
    title: "Bus Stop to Tapak Lelaki",
    pinpoint: [8],
    videoId: "Bo1xBK_iI40",
  },
  {
    id: 12,
    title: "Tandas Lelaki",
    pinpoint: [9],
    videoId: "TspHqsPowAc",
  },
  {
    id: 13,
    title: "Bus Stop",
    pinpoint: [8],
    videoId: "1DeJ5m_Rdi8",
  },
  {
    id: 14,
    title: "Cabin AJK Lelaki",
    pinpoint: [11],
    videoId: "xyS9mObeEVc",
  },
  {
    id: 15,
    title: "Video of Tapak Perkhemahan Lelaki",
    pinpoint: [10, 11],
    videoId: "nm3sDFP2oTw",
  },
  {
    id: 16,
    title: "Video of Tapak Perkhemahan Lelaki 2",
    pinpoint: [10],
    videoId: "S8PRtvVd35E",
  },
  {
    id: 17,
    title: "Riverside beside bus stop",
    pinpoint: [8],
    videoId: "NL3RFJB6xnk",
  },
  {
    id: 18,
    title: "Carpark, Surau and Route to Flying Fox",
    pinpoint: [12],
    videoId: "ZT8a98zFmWs",
  },
  {
    id: 19,
    title: "Carpark & Side of Pondok Pentadbiran",
    pinpoint: [2, 12],
    videoId: "rulwmnHAcOU",
  },
  {
    id: 20,
    title: "Tapak Perkhemahan Perempuan",
    pinpoint: [14],
    videoId: "bUNWJs9ea9Y",
  },
  {
    id: 21,
    title: "Route from Tapak Perkhemahan Perempuan to Pondok Pentadbiran",
    pinpoint: [12],
    videoId: "NlQQzfglqNI",
  },
  {
    id: 22,
    title: "Flying Fox Area",
    pinpoint: [15],
    videoId: "a3T7XTaZu_A",
  },
  {
    id: 23,
    title: "Route from Fancy Cabin to Gazebo",
    pinpoint: [16],
    videoId: "RJQghLfqYgk",
  },
  {
    id: 24,
    title: "Drop-off point from flying fox",
    pinpoint: [16],
    videoId: "X95cVgTB79U",
  },
  {
    id: 25,
    title: "Tribal council seats and route to Tapak Perkhemahan Perempuan",
    pinpoint: [14, 17],
    videoId: "HcITbcCVZZM",
  },

  {
    id: 26,
    title: "Route from bus stop to fancy cabin",
    pinpoint: [8, 18],
    videoId: "cTS4tHDA36o",
  },

  {
    id: 27,
    title: "Warning behind the fancy cabin",
    pinpoint: [18],
    videoId: "a0Z-0xgyVL0",
  },
];
