export const videos = [
  {
    id: 1,
    title: "Video from outside",
    pinpoint: [1],
    videoId: "Sp6Cdj7EyCw",
  },
  {
    id: 2,
    title: "Front view of the pentadbiran building",
    pinpoint: [2],
    videoId: "qXP-EnHWnmI",
  },
  {
    id: 3,
    title: "View of ground zero & entrace of dewan symphony",
    pinpoint: [3],
    videoId: "12Zh3EWWWxg",
  },

  {
    id: 4,
    title: "Dewan Video",
    pinpoint: [4],
    videoId: "TIK-e69Qbi0",
  },
  {
    id: 5,
    title: "Dewan Balcony Area",
    pinpoint: [4],
    videoId: "D5DK7DjUR7w",
  },
  {
    id: 6,
    title: "Kecekalan Track",
    pinpoint: [5],
    videoId: "hIIYDRpV-4s",
  },
  {
    id: 7,
    title: "Route to Kecekalan Track",
    pinpoint: [6],
    videoId: "B-9_GUhQeD4",
  },
  {
    id: 8,
    title: "Tapak QM",
    pinpoint: [6],
    videoId: "",
  },
  {
    id: 9,
    title: "Route to Tapak QM",
    pinpoint: [6, 7],
    videoId: "",
  },
  {
    id: 10,
    title: "QM Cooking Area",
    pinpoint: [6],
    videoId: "",
  },
  {
    id: 11,
    title: "Bus Stop to Tapak Lelaki",
    pinpoint: [8],
    videoId: "",
  },
  {
    id: 12,
    title: "Tandas Lelaki",
    pinpoint: [9],
    videoId: "",
  },
  {
    id: 13,
    title: "Bus Stop",
    pinpoint: [8],
    videoId: "",
  },
  {
    id: 14,
    title: "Cabin AJK Lelaki",
    pinpoint: [11],
    videoId: "",
  },
  {
    id: 15,
    title: "Video of Tapak Perkhemahan Lelaki",
    pinpoint: [10, 11],
    videoId: "",
  },
  {
    id: 16,
    title: "Video of Tapak Perkhemahan Lelaki 2",
    pinpoint: [10],
    videoId: "",
  },
  {
    id: 17,
    title: "Riverside beside bus stop",
    pinpoint: [8],
    videoId: "",
  },
  {
    id: 18,
    title: "Carpark, Surau and Route to Flying Fox",
    pinpoint: [12],
    videoId: "",
  },
  {
    id: 19,
    title: "Carpark & Side of Pondok Pentadbiran",
    pinpoint: [2, 12],
    videoId: "",
  },
  {
    id: 20,
    title: "Tapak Perkhemahan Perempuan",
    pinpoint: [14],
    videoId: "",
  },
  {
    id: 21,
    title: "Route from Tapak Perkhemahan Perempuan to Pondok Pentadbiran",
    pinpoint: [12],
    videoId: "",
  },
  {
    id: 22,
    title: "Flying Fox Area",
    pinpoint: [15],
    videoId: "",
  },
  {
    id: 23,
    title: "Route from Fancy Cabin to Gazebo",
    pinpoint: [16],
    videoId: "",
  },
  {
    id: 24,
    title: "Drop-off point from flying fox",
    pinpoint: [16],
    videoId: "",
  },
  {
    id: 25,
    title: "Tribal council seats and route to Tapak Perkhemahan Perempuan",
    pinpoint: [14, 17],
    videoId: "",
  },

  {
    id: 26,
    title: "Route from bus stop to fancy cabin",
    pinpoint: [8, 18],
    videoId: "",
  },

  {
    id: 27,
    title: "Warning behind the fancy cabin",
    pinpoint: [18],
    videoId: "",
  },
];
